-- NightWatch auth foundation (better-auth@1.6.23 core + organization + twoFactor)
--
-- ID policy: organizations are UUID tenants; every other ID column is text
-- carrying a UUID generated by Better Auth (`advanced.database.generateId`).
--
-- Privilege policy: this migration runs with the owner role. The runtime
-- role `nightwatch` is created by platform provisioning as
-- LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS and receives
-- least-privilege DML grants below. Auth tables are global (pre-tenant):
-- membership authorization is enforced by verified-membership lookups and
-- Better Auth's organization-bound queries before any tenant context is
-- established; they are intentionally not RLS tenant-scoped. RLS +
-- `app.tenant_id` applies to future domain tables only (see docs/architecture.md §3).

create table "user" (
  id text primary key,
  name text not null,
  email text not null,
  email_verified boolean not null default false,
  image text,
  two_factor_enabled boolean,
  last_active_tenant_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index user_email_lower_key on "user" (lower(email));

create table organization (
  id uuid primary key,
  name text not null,
  slug text not null unique,
  logo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

alter table "user"
  add constraint user_last_active_tenant_fkey
  foreign key (last_active_tenant_id) references organization (id) on delete set null;

create table session (
  id text primary key,
  expires_at timestamptz not null,
  token text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ip_address text,
  user_agent text,
  user_id text not null references "user" (id) on delete cascade,
  active_organization_id text
);

create index session_user_idx on session (user_id);

create table account (
  id text primary key,
  account_id text not null,
  provider_id text not null,
  user_id text not null references "user" (id) on delete cascade,
  access_token text,
  refresh_token text,
  id_token text,
  access_token_expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  scope text,
  password text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint account_provider_account_key unique (provider_id, account_id)
);

create index account_user_idx on account (user_id);

create table verification (
  id text primary key,
  identifier text not null,
  value text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index verification_identifier_idx on verification (identifier);

create table member (
  id text primary key,
  organization_id uuid not null references organization (id) on delete cascade,
  user_id text not null references "user" (id) on delete cascade,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- One membership per user per organization: makes concurrent invitation
  -- acceptance idempotent-safe at the SQL level.
  constraint member_organization_user_key unique (organization_id, user_id)
);

create index member_user_idx on member (user_id);

create table invitation (
  id text primary key,
  organization_id uuid not null references organization (id) on delete cascade,
  email text not null,
  role text not null,
  status text not null default 'pending',
  inviter_id text not null references "user" (id) on delete cascade,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index invitation_organization_idx on invitation (organization_id);

-- Invitation status lifecycle and duplicate/replay protection rely on
-- Better Auth's guarded pending -> accepted update plus the membership
-- unique constraint above; no extra partial-unique invitation constraint:
-- expired rows keep status 'pending' until reinvited, so uniqueness on
-- pending rows could permanently block a fresh invitation.

create table "twoFactor" (
  id text primary key,
  user_id text not null unique references "user" (id) on delete cascade,
  -- Encrypted TOTP secret and backup codes (keyed from BETTER_AUTH_SECRET).
  secret text not null,
  backup_codes text not null,
  verified boolean not null default false,
  failed_verification_count integer not null default 0,
  locked_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Least-privilege runtime grants. The runtime role is provisioned by
-- platform setup; grants are conditional so disposable/dev databases
-- without the role still migrate cleanly.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'nightwatch') then
    grant usage on schema public to nightwatch;
    grant select, insert, update, delete on
      "user", session, account, verification,
      organization, member, invitation, "twoFactor"
      to nightwatch;
  end if;
end $$;
