#!/usr/bin/env bun
/**
 * Local development dependency stack: isolated PostgreSQL + Mailpit SMTP
 * capture via Docker Compose. Every worktree gets its own compose project
 * (`nw-dev-<slot>`) and loopback-only ports from scripts/ports.mjs:
 *
 *   postgres  127.0.0.1:5400+slot   runtime role `nightwatch` (NOBYPASSRLS)
 *                                  owner role `nightwatch_owner` (DDL only)
 *   mailpit   127.0.0.1:7400+slot   SMTP capture
 *   mailpit   127.0.0.1:7500+slot   web UI (verification/reset/invite mail)
 *
 * Root aliases (package.json): db:up / db:down / db:logs / db:psql / db:mail.
 * Schema migrations are AuthServer-owned: `bun run db:migrate`.
 *
 * Generated development secrets are written once to .env.compose.local
 * (gitignored, mode 0600). Never commit them; production uses the approved
 * secret store, not this file.
 */
import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { readEnvFile } from "./env-file.mjs";
import { repoRoot, resolvePorts } from "./ports.mjs";

const LOCAL_ENV_PATH = resolve(repoRoot, ".env.compose.local");
const COMPOSE_FILE = resolve(repoRoot, "compose.yaml");

function secret() {
  return randomBytes(24).toString("hex");
}

/** Create the gitignored secrets file once; never overwrite existing secrets. */
function ensureLocalEnv() {
  if (existsSync(LOCAL_ENV_PATH)) return;
  const content = [
    "# Generated by scripts/db.mjs — local development secrets only.",
    "# Gitignored (see .gitignore). Production uses the approved secret store.",
    `NW_OWNER_PASSWORD=${secret()}`,
    `NW_DB_PASSWORD=${secret()}`,
    `BETTER_AUTH_SECRET=${secret()}`,
    "",
  ].join("\n");
  writeFileSync(LOCAL_ENV_PATH, content, { mode: 0o600 });
  chmodSync(LOCAL_ENV_PATH, 0o600);
  console.log(`[db] wrote ${LOCAL_ENV_PATH} (gitignored, mode 0600)`);
}

function compose(args) {
  const { slot, dbPort, mailSmtpPort, mailUiPort } = resolvePorts(process.env);
  const local = readEnvFile(LOCAL_ENV_PATH);
  const result = spawnSync("docker", ["compose", "-f", COMPOSE_FILE, ...args], {
    stdio: "inherit",
    env: {
      ...process.env,
      NW_SLOT: String(slot),
      NW_DB_PORT: String(dbPort),
      NW_MAIL_SMTP_PORT: String(mailSmtpPort),
      NW_MAIL_UI_PORT: String(mailUiPort),
      NW_OWNER_PASSWORD: local.NW_OWNER_PASSWORD ?? "",
      NW_DB_PASSWORD: local.NW_DB_PASSWORD ?? "",
    },
  });
  if (result.error) {
    console.error(`[db] failed to run docker compose: ${result.error.message}`);
    process.exit(1);
  }
  process.exit(result.status ?? 1);
}

const [, , command, ...rest] = process.argv;
ensureLocalEnv();
const ports = resolvePorts(process.env);

switch (command) {
  case "up":
    compose(["up", "-d", "--wait", ...rest]);
    break;
  case "down":
    compose(["down", ...rest]);
    break;
  case "logs":
    compose(["logs", "-f", ...rest]);
    break;
  case "psql":
    compose([
      "exec",
      "postgres",
      "psql",
      "-U",
      "nightwatch_owner",
      "-d",
      "nightwatch",
      ...rest,
    ]);
    break;
  case "mail":
    console.log(
      `[db] Mailpit: http://localhost:${ports.mailUiPort} (SMTP 127.0.0.1:${ports.mailSmtpPort})`,
    );
    break;
  case "env":
    console.log(`[db] secrets file: ${LOCAL_ENV_PATH} (gitignored)`);
    console.log(
      `[db] project nw-dev-${ports.slot} · postgres 127.0.0.1:${ports.dbPort} · mailpit UI http://localhost:${ports.mailUiPort}`,
    );
    break;
  default:
    console.error(
      "usage: bun scripts/db.mjs <up|down|logs|psql|mail|env> [-- extra compose args]",
    );
    process.exit(2);
}
